### ISSUE TITLE
Support for Windows?

### ISSUE THREAD

**Issue by dylandarken** [chengchingwen/Raylib.jl#25]
This is a very promising package, but it doesn't work on Windows.

I tried to run the core/basic_window.jl example and got the following error:

`UndefVarError: libraylib not defined`

I'm assuming Raylib_jll is not available for windows, do you plan to support this package on Windows too?

**Comment by chengchingwen** [comment]
Unfortunately we failed to build the Windows version with BinaryBuilder and I'm totally unfamiliar with Windows' building environment.

If anyone is interested in making Windows version work, you can find the current building script [here](https://github.com/JuliaPackaging/Yggdrasil/tree/master/R/Raylib)

**Comment by dylandarken** [comment]
I understand, building on Windows without Visual Studio is a pain. 

Should i close this issue?

**Comment by chengchingwen** [comment]
Let's keep it open.

**Comment by jakkosdev** [comment]
I tried out the BinaryBuilder script for windows and the makefile just seems to silently fail. I might try and investigate more when I have time. Did you have any idea what could be causing the problem or suggestions for where to look first?

**Comment by chengchingwen** [comment]
> Did you have any idea what could be causing the problem or suggestions for where to look first?

Unfortunately no, I don't even have a windows machine at hand. But there is a `BinaryBuilder.run_wizard()` that can run a windows container. You can test/investigate the compilation in that container and see what goes wrong. The building instructions can be found in the [building script](https://github.com/JuliaPackaging/Yggdrasil/blob/master/R/Raylib/build_tarballs.jl#L16)

**Comment by jakkosdev** [comment]
So I'm a little bit out my depth here, but think I've made some progress, I can now build libraylib.dll  with the build script for windows 32 and 64 bit.

A few quick questions:

-  Is the generated libraylib.dll the only file we need to copy into the destdir at the end? `make install` doesn't work for the raylib makefile on windows, so I was just manually copying over the dll to destdir at the end.
- Do we need to have `USE_EXTERNAL_GLFW=TRUE` in the make flags? for some reason this breaks on windows.
- If I think I have a working build script, what's the best way to test it out with Raylib.jl to make sure before I submit a pull request to Yggdrasil?

**Comment by chengchingwen** [comment]
Sounds like some good news!

> Is the generated libraylib.dll the only file we need to copy into the destdir at the end? make install doesn't work for the raylib makefile on windows, so I was just manually copying over the dll to destdir/bin at the end.

There are two part of files that need to be copied at the end. One is the libraylib that should be copied to a `lib` folder. Another part is the headers (`physac.h`, `raygui.h`, `raylib.h`, `raymath.h`, and `rlgl.h`) that should be copied to a `include` folder. These folder are probably under the destdir, though I don't remember the full path. You could check with the BinaryBuilder wizard (it would told you if you didn't copy any files to it's product folder).

> Do we need to have USE_EXTERNAL_GLFW=TRUE in the make flags? for some reason this breaks on windows.

By setting the `USE_EXTERNAL_GLFW` flag, it would use the GLFW managed by Julia (GLFW_jll). But if that is unworkable on windows, I think we can just turn that off for windows building script.

> If I think I have a working build script, what's the best way to test it out with Raylib.jl to make sure it works before I submit a pull request to Yggdrasil?

Running the julia build script with `--deploy=local` as mentioned [here](https://docs.binarybuilder.org/stable/building/#Building-a-custom-JLL-package-locally). This would generate a Raylib_jll, and then cloning Raylib.jl and make sure it load the generated one.

**Comment by jakkosdev** [comment]
![image](https://user-images.githubusercontent.com/45759112/169647561-acca8ae5-14c7-4d84-a12d-4649c97766ed.png)
Seem to have got it to work, made a pull request :)
https://github.com/JuliaPackaging/Yggdrasil/pull/4929

**Comment by chengchingwen** [comment]
@jakkosdev I don't know why your comment disappeared, but I see that PR. Great works! Thanks!

**Comment by chengchingwen** [comment]
Since Yggdrasil merged, now it should be supported on Windows.
